### PR TITLE
Added extension method ToMaybe<string>

### PR DESCRIPTION
**Pull request by petrkoutnycz**
We'd like to have more convenient way of creating Maybe<string> instances, thus this extension method. Thanks :-)

### CODE REVIEW

**Comment by petrkoutnycz** [comment]
@kruglik-alexey @khmylov Guys, can you take a look at this subtle change, please?

**Comment by petrkoutnycz** [comment]
@alex-fomin ping :)

**Comment by khmylov** [comment]
Hi Petr, thank you for your contribution.

However, I think that treating empty string as `Nothing` _by default_ doesn't fit into the primary goal of `Maybe` module, which is to effectively lift the absence of value into the type system and avoid `null` values where possible. Empty string and `null` string are conceptually different to me.

If you find this behavior useful for your scenarios though, you can have such extension method in your code base :)

**Comment by petrkoutnycz** [comment]
@khmylov Well we can change the default value of the parameter to be `false`, right? :)

**Pull request closed without merging**
